/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jalpeshrajani' at '2/9/18 6:55 PM' with Gradle 2.13
 *
 * @author jalpeshrajani, @date 2/9/18 6:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
